# Generated by Django 4.1.6 on 2023-03-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='author',
            name='profileImage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
