# Generated by Django 4.1.6 on 2023-03-01 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id',
            new_name='comment_id',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='id',
            new_name='like_id',
        ),
    ]
