
# Generated by Django 4.1.6 on 2023-03-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content_type',
            new_name='contentType',
        ),
    ]
