# Generated by Django 4.1.6 on 2023-03-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='object',
            field=models.URLField(editable=False, max_length=300, null=True),
        ),
    ]
