# Generated by Django 4.1.6 on 2023-03-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
