# Generated by Django 4.1.6 on 2023-03-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('text/markdown', 'text/markdown'), ('text/plain', 'text/plain'), ('application/base64', 'application/base64'), ('image/png;base64', 'image/png;base64'), ('image/jpeg;base64', 'image/jpeg;base64'), ('multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW', 'multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW')], default='text/plain', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
