# Generated by Django 4.1.6 on 2023-03-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
