# Generated by Django 4.1.6 on 2023-02-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=200)),
                ('displayName', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('github', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(default='blank_profile.png', null=True, upload_to='profile_images')),
            ],
        ),
    ]
