# Generated by Django 4.1.6 on 2023-03-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_is_active_author_is_staff_author_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='author',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
