# Generated by Django 4.1.6 on 2023-03-01 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_remove_author_is_active_remove_author_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
