# Generated by Django 4.1.6 on 2023-03-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_user_displayname_user_github_user_host_user_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
