# Generated by Django 4.1.6 on 2023-03-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_remove_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='displayName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='github',
        ),
        migrations.RemoveField(
            model_name='user',
            name='host',
        ),
        migrations.RemoveField(
            model_name='user',
            name='url',
        ),
    ]
