# Generated by Django 4.1.6 on 2023-03-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('team_num', models.IntegerField(primary_key=True, serialize=False)),
                ('api_url', models.CharField(blank=True, max_length=255, null=True)),
                ('api_author_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_token', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
