# Generated by Django 4.1.6 on 2023-03-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
